version: '3.8'
# This is used for the local build and for local setting up
services:
  xai-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - LOG_LEVEL=INFO
    volumes:
      # Mount ML models from local system
      - ../../../ml/models/xai_predictor:/app/models:ro
      # Mount app for hot reload during development
      - ./app:/app/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload